# Generated by Django 2.0.13 on 2019-05-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sidemenus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
